spring.application.name=web
spring.datasource.url=jdbc:postgresql://postgres:5432/banco
spring.datasource.username=andres
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=validate
management.endpoints.web.exposure.include=health
spring.jpa.properties.jakarta.persistence.validation.mode=AUTO
logging.level.web.exception=INFO
logging.level.web.filter=INFO