spring.application.name=web
spring.datasource.url=jdbc:postgresql://postgres:5432/banco
spring.datasource.username=andres
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.jakarta.persistence.validation.mode=AUTO
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.web.exception=INFO
logging.level.web.filter=INFO